buttons:
  - name: a
    pin: 12
    value: 2 # xbox b button
  - name: x
    pin: 16
    value: 4 # xbox y button
  - name: b
    pin: 6
    value: 1 # xbox a button
  - name: y
    pin: 13
    value: 3 # xbox x button
sticks:
  - name: left
    x_channel: 0
    y_channel: 1
    deadzone: 700
